### ISSUE TITLE
semvers with build metadata are unmarshalled incorrectly

### ISSUE THREAD

**Issue by pablochacin** [grafana/k6deps#43]
`k6deps.Dependencies.UnmarshalText` will truncate semvers that specifying build metadata:

For `k6=v0.0.0+90bb941`, the version is returned as `v0.0.0+90`.
For `k6=v0.0.0+135f85b`  the version is returned as `v0.0.0+135`

**Comment by szkiba** [comment]
I'm afraid the situation is worse, part of the metadata is lost during parsing. The constraints expression is matched with the following regular expression:

```go
srcConstraint = `[vxX*|,&\^0-9.+-><=, ~]+`
```

This shows that the build metadata will end at the first non-digit character.

This can be considered an error. However, it can also be considered that this never happens, because version constraints will never contain build metadata. Namely, build metadata cannot participate in the comparison. According to the semver specification:

> Build metadata MUST be ignored when determining version precedence. 

Further consideration is needed as to what happens to the build metadata. Should this bug be fixed and, despite the specification, should the build metadata also participate in the version comparison or not?

**Comment by szkiba** [comment]
It is possible that an exception should be made for v0.0.0 and only then should the build metadata be accepted in the version constraints. I think this is the use case. This much deviation from the specification can be accommodated.

**Comment by szkiba** [comment]
@pablochacin,  fixed in k6deps v0.1.8
k6exec also released (v0.1.11) to contain this fix
